# Generated by Django 4.2.4 on 2023-08-14 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("water_reminder_api", "0002_waterconsumptiondaily"),
    ]

    operations = [
        migrations.RenameField(
            model_name="waterconsumptionhistory",
            old_name="comsumption_ml",
            new_name="consumption_ml",
        ),
    ]
